sequence = "PPEVAVFEPSEAEISHTQKATLVCLATGFYPDHVELSWWVNGKEVHSGVCTDPQPLKEQPALNDSRYALSSRLRVSATFWQNPRNHFRCQVQFYGLSENDEWTQDRAKPVTQIVSAEAWGRAD"
n = 1 
for i in range(len(sequence)):
    print(f"Position {n}: {sequence[i]}")
    n += 1